[package]
name = "kura"
edition = "2024.beta"

[dependencies.Sui]
git = "https://github.com/MystenLabs/sui.git"
subdir = "crates/sui-framework/packages/sui-framework"
rev = "framework/mainnet"

[addresses]
kura = "0x0"
sui = "0000000000000000000000000000000000000000000000000000000000000002"
